packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'
overrides:
  '@tiptap/core': 3.31.3
  '@tiptap/pm': 3.31.3
  fast-uri: 3.1.6
  hono: 4.13.8
  multer: 2.4.0
  qs: 6.16.0
allowBuilds:
  '@swc/core': true
  argon2: true
  unrs-resolver: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
  msw: true
minimumReleaseAgeExclude:
  - '@testing-library/jest-dom@7.0.0'
  - '@typescript-eslint/eslint-plugin@8.65.0'
  - '@typescript-eslint/parser@8.65.0'
  - '@typescript-eslint/project-service@8.65.0'
  - '@typescript-eslint/scope-manager@8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0'
  - '@typescript-eslint/type-utils@8.65.0'
  - '@typescript-eslint/types@8.65.0'
  - '@typescript-eslint/typescript-estree@8.65.0'
  - '@typescript-eslint/utils@8.65.0'
  - '@typescript-eslint/visitor-keys@8.65.0'
  - typescript-eslint@8.65.0
