import { ulid } from 'ulid';

/**
 * Per ADR-0003 "Kimlik stratejisi": the object's business identity (`id`) is
 * a ULID (zero-time-sortable, distinct from the event-stream UUID
 * `streamId`). Generated by the domain but passed as an argument into
 * `createObject` so commands stay pure/deterministic.
 */
export function newObjectId(): string {
  return ulid();
}
